[project]
name = "nanoagents"
version = "0.1.0"
description = "A multi-agent framework built just for educational and learning purpose"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.33.0",
    "pydantic>=2.13.3",
    "requests>=2.33.1",
    "typing-extensions>=4.15.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort/import sorting
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"